package org.LogAggregatorTool.constants;

public class LogAggregatorConstants {
    public static String BACK_SLASH = "\\";
    public static String COMA = ",";
    public static String DATABASE_ERROR = "Database Error.";
    public static String DATE_FORMAT = "yyyy/MM/dd HH:mm:ss:SSS";
    public static int DEFAULT_INT_VALUE = 0;
    public static String EMPTY_STRING = "";
    public static String ENTER_OUTPUT_FILE_PATH = "\nPlease enter a path to store output file : ";
    public static String ENTER_PATH_MESSAGE = "Please enter a path to the folder which contains logFiles : ";
    public static String EXCEPTION_MESSAGE = "Error in reading files.";
    public static String EXIT_MESSAGE = "You have chosen to exit.";
    public static String FAILURE = "Failure";
    public static String FAILURE_MESSAGE = "Failure : ";
    public static String INVALID_DIRECTORY = "Invalid Directory.";
    public static String INVALID_DIRECTORY_MESSAGE = " is not a path to a folder.";
    public static String INVALID_FILE = "Invalid file.";
    public static String INVALID_FILE_MESSAGE = " is not a file. Provided input path contains folder.";
    public static String INVALID_FILE_FORMAT = "Invalid file format.";
    public static String INVALID_FILE_FORMAT_MESSAGE = " file is in wrong Format.";
    public static String INVALID_PATH = "\nInvalid! Path does not exist.\nPlease try again or enter e to exit : ";
    public static String IO_EXCEPTION_MESSAGE = "Input Output Exception : ";
    public static int LENGTH_OF_DATE = 10;
    public static int LENGTH_OF_TIMESTAMP = 23;
    public static String LOG_FILE_EXTENSION = ".log";
    public static String NEW_DATE_FORMAT = "MM/dd/yyyy HH:mm:ss.SSS";
    public static String NEW_LINE_CHAR = "\n";
    public static String PROCESSING_MESSAGE = "Processing...";
    public static String REGEX_TO_MATCH_DATE_FORMAT = "[1-9][0-9][0-9]{2}/(0[1-9]|1[0-2])/([1-2][0-9]|0[1-9]|3[0-1])";
    public static String REGEX_TO_MATCH_NEW_DATE_FORMAT = "(0[1-9]|1[0-2])/([1-2][0-9]|0[1-9]|3[0-1])/[1-9][0-9][0-9]{2}";
    public static String SPACE = " ";
    public static String SUCCESS = "Success";
    public static String SUCCESS_MESSAGE = "Success!!!All the files are merged\nThe location of the output file is : ";
    public static String TEXT_FILE_EXTENSION = ".txt";
    public static String THANK_YOU_MESSAGE = "Thanks for using LogAggregatorTool.";
    public static String TO_EXIT = "e";
    public static String USER_EXIT_MESSAGE = "User has chosen to exit.";
    public static String WELCOME_MESSAGE = "Welcome to Log Aggregator Tool\nNote : Ensure that all the paths you provide are valid.";
}
